// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: alert_daily_schedule.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAlertDailySchedule = `-- name: InsertAlertDailySchedule :exec
INSERT INTO alerts_daily_schedule (item_id, discord_id, is_active)
VALUES($1, $2, true)
`

type InsertAlertDailyScheduleParams struct {
	ItemID    pgtype.Int4
	DiscordID pgtype.Int8
}

func (q *Queries) InsertAlertDailySchedule(ctx context.Context, arg InsertAlertDailyScheduleParams) error {
	_, err := q.db.Exec(ctx, insertAlertDailySchedule, arg.ItemID, arg.DiscordID)
	return err
}
