// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: game.sql

package repository

import (
	"context"
)

const getGameList = `-- name: GetGameList :many
SELECT games.id, games.game_name, games.game_icon_url FROM games
LIMIT 10
`

func (q *Queries) GetGameList(ctx context.Context) ([]Game, error) {
	rows, err := q.db.Query(ctx, getGameList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(&i.ID, &i.GameName, &i.GameIconUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
