// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Game struct {
	ID          int64
	GameName    string
	GameIconUrl string
}

type Session struct {
	ID           int64
	IsFinish     pgtype.Bool
	SessionEnd   pgtype.Timestamp
	SessionStart pgtype.Timestamp
	CreatedBy    int64
	GameID       int64
	CreatedAt    pgtype.Timestamptz
}

type User struct {
	ID         int64
	Username   string
	AvatarUrl  string
	DiscordUid int64
}

type UsersSession struct {
	UserID    int64
	SessionID int64
}
